### PR TITLE
Reorganise Bubble Sort functionality into header file

### PR DESCRIPTION
**Pull request by limepixl**
- [x] Read the [contribution guidelines][contrib-guidelines]
- [ ] Added [unit tests][unit-tests] (or unit tests have already been added)
- [ ] Updated the [Contents][contents]

[contrib-guidelines]: https://github.com/faheel/Algos/blob/master/CONTRIBUTING.md
[unit-tests]: https://github.com/faheel/Algos/blob/master/C%2B%2B/UNIT_TESTS.md
[contents]: https://github.com/faheel/Algos/tree/master/C%2B%2B#contents

### CODE REVIEW

**Comment by alxmjo** [comment]
@limepixl Thanks for your work on this! @Faheel is the brains behind this operation, so he may contradict me, but I think what we're looking for here is to have all of the algorithms implemented as header files. 

So there would just be 
`C++/include/sorting/bubble_sort.hpp`.  (Edit: Come to think of it, maybe this should be under `C++/include/algorithm/sorting/bubble_sort.hpp`. @faheel?)

For unit testing, we'll have `C++/test/sorting/bubble_sort.cpp`. This unit testing file won't have a `main()`. Instead, it'll employ test cases using `Catch.hpp`. Does that make sense?

**Comment by limepixl** [comment]
@alxmjo Yes, it does. I'll make the needed changes as soon as I can. 

Thanks for replying!

**Comment by alxmjo** [comment]
Sounds good. Let us know if you have any other questions.

Also, if you dig into the repo you'll find some test cases for bubble sort. Feel free to repurpose those and add them to this PR.

**Comment by alxmjo** [comment]
This is the PR I was referring to: https://github.com/faheel/Algos/pull/168

**Comment by alxmjo** [comment]
@limepixl Are you closing to make changes? Or are you not moving forward with this?

**Comment by limepixl** [comment]
Sorry, I didn't explain beforehand.
I wanted to close the pull request so I can make a different one containing all sorting algorithm headers instead of doing just the Bubble Sort algorithm. 

Would that be okay?

**Comment by alxmjo** [comment]
@limepixl No worries. Probably best to keep the PRs narrow and specific to a single algorithm. Your efforts will be similar from algorithm to algorithm, but it'll be easier to keep organized.

**Comment by limepixl** [comment]
After reviewing my progress so far (most of the sorting algorithms currently), I realize it's nowhere near the quality standard, so I won't be opening another pull request. I apologize for the time wasted (if any).

**Comment by alxmjo** [comment]
No time wasted, at least not on our end! Please let us know if there's anything we can do to help get you involved with the repo. We're happy to help.

**Pull request closed without merging**
