### PR TITLE
BigInt implementation

### PR DESCRIPTION
**Pull request by seanhouser**
Followed instructions provided to begin work on BigInt class

### CODE REVIEW

**Comment by faheel** [comment]
You merged `dev` with the updated `master` -- don't do that! You can revert the previous commit and pull from `upstream/dev` to update your fork.

**Comment by seanhouser** [comment]
My fault, thank you for letting me know. I'm still new to using Git. I assume you have undone the changes I made because when I try to Revert it fails. Let me know if you need me to do anything on my end. Again, apologies for the error.

**Comment by faheel** [comment]
I haven't made any changes on my end yet, so there's no problem for me. You should however try to revert the changes that were made when you did the merge because later, when the PR is to be merged, there may be lots of conflicts to be fixed!

A simple fix is to remove the files that were added during the merge and then do `git add --all` and then commit. But a better and recommended solution is to do an [interactive rebase](https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history) and drop the commits that you do not want to include.

**Comment by seanhouser** [comment]
I followed your suggestion and have your updated `dev` branch back on my machine, thank you. I see that you merged the changes the other user suggested for relational operations, however those changes cause issues with some of the operations I've already completed. No worries though, I will write my own relational operators and add them to my PR for your review. Thanks again for the explanation, and sorry for today's little learning experience!

**Comment by faheel** [comment]
Can you push the changes you have made so far so that I can take a look?

**Comment by seanhouser** [comment]
Gladly! One moment, please.

**Comment by seanhouser** [comment]
I believe I've made an error. Before you edited your comment to recommend an interactive rebase I followed your suggestion to remove and re-add files locally. I elected to do this by re-cloning the repo. Unfortunately this appears to have removed me from this PR and I am unsure how to push additional commits to it. I can create a new PR, but obviously that wouldn't be ideal. I committed to faheel/dev before realizing it was not part of a PR, and have reverted that change. I am researching how to make commits to an existing PR now.

**Comment by seanhouser** [comment]
Ok, got it figured out (with an accidental revert and "revert revert"). Thanks for your patience

**Comment by faheel** [comment]
OK, good. Now you need to rebase from the `Add string algorithms` commit (which would probably be `HEAD~12`) and drop the first 4 commits from there.

**Comment by seanhouser** [comment]
Will do. Before I issue the drop commands I would like to confirm I am dropping the correct commits. Here are the commits I can drop from `~HEAD12`. Please advise which commits need to be dropped. 

```
pick 8755240 Add .md extension
pick 6c31e86 Add contributing guidelines
pick becaaf5 Update README
pick 9c1f11d Add big integer data structure, BigInt
pick 726643d Cursory changes
pick d408eb1 Progress
pick b2d6caf Addition operations on signed BigInts complete with testing
pick 5682026 Multiplication operations on signed BigInts complete with testing
pick be5103b Add string algorithms
pick 642d051 Cleanup license section
pick ad259da Rename and move KMP
pick 19a85c8 Refactor code
pick 38c239a Revert "Multiplication operations on signed BigInts complete with testing"
pick 1ec9ca2 Revert "Revert "Multiplication operations on signed BigInts complete with testing""
pick f31aaaa Progress
```

**Comment by faheel** [comment]
Looking at your log, it would be sufficient to rebase from `HEAD~8` with the following changes:
```
pick 5682026 Multiplication operations on signed BigInts complete with testing
drop be5103b Add string algorithms
drop 642d051 Cleanup license section
drop ad259da Rename and move KMP
drop 19a85c8 Refactor code
squash 38c239a Revert "Multiplication operations on signed BigInts complete with testing"
squash 1ec9ca2 Revert "Revert "Multiplication operations on signed BigInts complete with testing""
squash f31aaaa Progress
```

**Comment by seanhouser** [comment]
Rebase from `HEAD~8` completed, however I received conflict errors on the pick and first 2 squash commands (`38c239a` and `1ec9ca2`). Let me know if we're all set or if you have further instructions for me.

**Comment by faheel** [comment]
Dropping the following may solve the conflict:
```
...
drop 38c239a Revert "Multiplication operations on signed BigInts complete with testing"
drop 1ec9ca2 Revert "Revert "Multiplication operations on signed BigInts complete with testing""
...
```

**Comment by seanhouser** [comment]
Thank you. I have successfully dropped `38c239a` and `1ec9ca2` from `HEAD~8` without errors. Shall I retry those 3 commands now? Or are we all set?

**Comment by faheel** [comment]
You would now need to push your commits to know whether we're all set or not :sweat_smile:

**Comment by seanhouser** [comment]
Well that makes sense! Alright, commits pushed. Hopefully that gets us where we need to be! Thanks again for your patience, this was a lot to take in as a Git user unfamiliar with most collaboration features.

**Comment by faheel** [comment]
Sadly, the files are still present in the PR :cry: 

I suggest that you close this PR, copy the code you wrote, delete the current branch, update your `dev` branch, create a new branch from `dev`, add your code there, and open a new PR.

**Comment by seanhouser** [comment]
I'll do exactly that, you should see a new PR from me shortly.

**Pull request closed without merging**
