### PR TITLE
Added Euclidean algorithm for computing GCD of 2 numbers

### PR DESCRIPTION
**Pull request by Rushyendher**

### CODE REVIEW

**Comment by faheel** [comment]
Your pull request also has some files that you may not have wanted to add, such as Sieve of Eratosthenes (it has been already been merged).

I recommend that you first [sync you fork](https://help.github.com/articles/syncing-a-fork/) and then add and commit the GCD program.

**Comment by Rushyendher** [comment]
Sorry I am new to GIT and learning it.

**Comment by faheel** [comment]
The file is still there because the commit hasn't been _dropped_.

You need to do `git rebase -i HEAD~5` and then **drop** the commits related to _Sieve of Eratosthenes_ and **squash** the commits related to the merge you made to sync your fork.

Read the [documentation for _interactive rebase_](https://git-scm.com/docs/git-rebase#_interactive_mode) to know more.

Your interactive rebase should read something like the following before you save:
```
drop Add Sieve Of Eratosthenes to generate prime numbers upto given number,N.
drop Add Space and Time complexity to Seive of Eratosthenes
pick Add Euclidean algorithm for computing GCD
squash Merge remote-tracking branch 'upstream/master'
squash Merge branch 'master' of https://github.com/Rushyendher/Algos
```
Then when it asks to enter (or change) the final commit message, you can change it to:
> `Add Euclid's algorithm for computing GCD`

**Comment by faheel** [comment]
@Rushyendher Any progress on this yet?

**Comment by faheel** [comment]
Closing this since GCD's implementation was added in PR #44.

**Pull request closed without merging**
