### PR TITLE
Added Euler's Totient Function

### PR DESCRIPTION
**Pull request by naveensaigit**
Added an implementation of Euler's Totient Function

- [ x] Read the [contribution guidelines][contrib-guidelines]
- [x] Added [unit tests][unit-tests] (or unit tests have already been added)
- [x ] Updated the [Contents][contents]

[contrib-guidelines]: https://github.com/faheel/Algos/blob/master/CONTRIBUTING.md
[unit-tests]: https://github.com/faheel/Algos/blob/master/C%2B%2B/UNIT_TESTS.md
[contents]: https://github.com/faheel/Algos/tree/master/C%2B%2B#contents

### CODE REVIEW

**Comment by alxmjo** [comment]
Thanks for contributing, @naveensaigit. While you're waiting on this, please write [unit tests](https://github.com/faheel/Algos/blob/master/C%2B%2B/UNIT_TESTS.md) for the algorithm so that we can verify that it's correct. 🙂

**Comment by naveensaigit** [comment]
Yeah, I will add unit tests for it soon

**Comment by naveensaigit** [comment]
I have added the unit tests. However, as I am new on GitHub, I created another pull request(by mistake) while modifying the README file. Is there a possibility for both of them to be merged?

**Comment by alxmjo** [comment]
One of the cool things bout GitHub and PR's is that whenever you push to the same branch you opened the PR with, those new changes will automatically be incorporated into the original PR. 

So, rather than merging these separately, why don't you incorporate the changes to the README into this branch, commit, push, and then they'll be reflected in this PR. Does that make sense? And you can close the other PR.

**Comment by naveensaigit** [comment]
Yes, I did that. I updated both README and CMakeLists. Thanks for the advice!

**Pull request closed without merging**
