### PR TITLE
Primorial algorithm

### PR DESCRIPTION
**Pull request by janos-laszlo**
Added the algorithm for calculating the primorial value of a prime number, given a prime number or a prime number index.

### CODE REVIEW

**Comment by faheel** [comment]
There have been lots of suggestions recently by interested contributors to add more algorithms and data structures to the project, which I have currently put on hold because I want to close issue #74 first, as it would require a complete reorganisation of files and some refactoring of code.

I previously thought that I would work on #74 once the currently active PRs are merged, but I feel that it would take much longer that way. So, if it's not too inconvenient for you, I would like to work on issue #74 as soon as possible. The remaining work on this PR (and others) can be carried on afterwards. Once the project is refactored, all you would need to do is `git fetch upstream` and move the code that you wrote to the new appropriate directory.

So, what do you say?

**Comment by janos-laszlo** [comment]
It's ok.

**Comment by faheel** [comment]
The changes have been made. Please sync your branch with the changes.

**Comment by faheel** [comment]
Closing this due to lack of activity for a long time.

**Pull request closed without merging**
