### PR TITLE
Tower Of Hanoi

### PR DESCRIPTION
**Pull request by ShumWengSang**
Here is an implementation of the Tower of Hanoi using recursive functions.

### CODE REVIEW

**Comment by faheel** [comment]
Looks like the Tower of Hanoi source file has been replaced by point quad tree.

**Comment by ShumWengSang** [comment]
Ehhh I'm actually preetty confused over how a Pull Request worked... I was
trying to submit a new pull request, but I already had one before from the
Tower of Hanoi. Should I resubmit something?

**Comment by faheel** [comment]
I've updated the README to include one important piece of information which was missing - that you have to create a new branch for each algorithm you're contributing. This enables you to send multiple PRs, each regarding a different algorithm or data structure.

What I suggest now is that you:
1. close this PR
1. copy the files you've added to some other location on your PC
1. rebase and drop the commits you've made
1. update your copy of the repo
1. create a new branch and add the files related to the first algorithm
1. commit and push the changes to GitHub
1. switch back to the `master` branch
1. create another branch and add the files related to the other algorithm
1. commit and push the changes to GitHub
1. make your PRs from GitHub by switching to the branches that you made

As a beginner, these may seem intimidating, but it's really not that difficult and will allow you to learn more about using Git. I also suggest that you read about the [GitHub flow](https://help.github.com/articles/github-flow/).

**Comment by ShumWengSang** [comment]
I THINK I did it. Created two branches with two separate pull requests.
Thanks for the help!

**Pull request closed without merging**
