### PR TITLE
Added linked list algorithms

### PR DESCRIPTION
**Pull request by ghost**
Copy And Move Constructors have been added for SinglyLinkedList - following The Rule of Big Three, along with Copy and Swap for Assignment operator; some indentation issues have been resolved, also compilation errors have been removed, and Algorithm to reverse the list has been added.

- [x] Read the [contribution guidelines][contrib-guidelines]
- [ ] Added [unit tests][unit-tests] (or unit tests have already been added)
- [ ] Updated the [Contents][contents]

[contrib-guidelines]: https://github.com/faheel/Algos/blob/master/CONTRIBUTING.md
[unit-tests]: https://github.com/faheel/Algos/blob/master/C%2B%2B/UNIT_TESTS.md
[contents]: https://github.com/faheel/Algos/tree/master/C%2B%2B#contents

### CODE REVIEW

**Comment by alxmjo** [comment]
Thanks for contributing, @jsahil730. We already have data structures for singly and doubly linked lists. If you'd like to contribute something else, please do so. You can find our contribution guidelines [here](https://github.com/faheel/Algos/blob/master/README.md).

**Comment by faheel** [comment]
These changes are actually minor enhancements to the existing implementation of singly linked list. I'm reopening the PR and will review the code in detail when I get time.

**Comment by alxmjo** [comment]
My mistake. Thanks for catching that.

**Comment by alxmjo** [comment]
Looks like there are some merge conflicts here. Once you resolve those we can do a formal review. Thanks.

**Comment by alxmjo** [comment]
Closing for now. Please feel free to reopen once merge conflicts are sorted out.

**Pull request closed without merging**
