### PR TITLE
Add sorting tests

### PR DESCRIPTION
**Pull request by camilne**
Added tests for the sorting algorithms. See #129, which hasn't been updated for 5 months.

- [x] Read the [contribution guidelines][contrib-guidelines]
- [x] Added [unit tests][unit-tests] (or unit tests have already been added)
- [x] Updated the [Contents][contents]

[contrib-guidelines]: https://github.com/faheel/Algos/blob/master/CONTRIBUTING.md
[unit-tests]: https://github.com/faheel/Algos/blob/master/C%2B%2B/UNIT_TESTS.md
[contents]: https://github.com/faheel/Algos/tree/master/C%2B%2B#contents

### CODE REVIEW

**Comment by camilne** [comment]
Note that the radix sort test fails, but this is because radix sort is broken (a couple of parameters are being passed incorrectly within the function).

**Comment by faheel** [comment]
@camilne Thanks for contributing! As I mentioned in #163 I am reorganising most of the code to facilitate maximum code reuse. Also, from the discussion for sorting tests in #157, it'll be good that tests reuse as much code as possible too. So I suggest that you wait until #163 is closed and then we'll discuss this PR. Again, thanks for deciding to contribute but I suggest commenting on an existing issue or creating one yourself before creating a PR so that you can be pointed in the right direction as to what next steps you should take.

**Comment by faheel** [comment]
And yes, thanks for pointing out that radix sort is broken. Please create a new issue for it so that others can look into it and maybe we get a fix for it soon.

**Comment by alxmjo** [comment]
Sorting tests added in #251.

**Pull request closed without merging**
