### PR TITLE
Migrate extended Euclidean algorithm

### PR DESCRIPTION
**Pull request by alxmjo**
Migrate extended Euclidean algorithm to header file (as described in #163).

- [x] Read the [contribution guidelines][contrib-guidelines]
- [x] Added [unit tests][unit-tests] (or unit tests have already been added)
- [x] Updated the [Contents][contents]

[contrib-guidelines]: https://github.com/faheel/Algos/blob/master/CONTRIBUTING.md
[unit-tests]: https://github.com/faheel/Algos/blob/master/C%2B%2B/UNIT_TESTS.md
[contents]: https://github.com/faheel/Algos/tree/master/C%2B%2B#contents

### CODE REVIEW

**Comment by faheel** [comment]
@alxmjo Please rebase this with the latest changes from `reorganise`.

**Comment by alxmjo** [comment]
@faheel Not sure why this ended up bringing in the older version of the greatest common divisor files. This is what it looks like for me locally: https://github.com/alxmjo/Algos/commit/11cce2200ac6fd03efdeb06015a1119bb923cd0a

**Comment by alxmjo** [comment]
I think it's OK now. Apologies for the mixup.

**Comment by ankur54** [comment]
Can anyone please specify the work/issue at hand? I would like to start working on it.

**Comment by ankur54** [comment]
How can I contribute to it? Please explain!!

**Comment by alxmjo** [comment]
@ankur54 This is closed and no work needs to be done. I just shared it as a reference for how to go about refactoring the code into header files.

**Comment by ankur54** [comment]
ok! So what about Lowest common ancestor in Binary Search tree? Is it also completed?

**Comment by alxmjo** [comment]
If you see it in the `reorganise` branch under `/include`, then yes. If not, no. But I do know that @faheel had planned some reorganisation with regards to graphs, so he's the authority on that.

**Comment by ankur54** [comment]
I'm sorry, but I can't find any such file. So I assume its still not resolved. In that case, I would like to work on it.

**Comment by alxmjo** [comment]
No problem, I just didn't take the time to check myself. 🙂Please do. But start an issue for it first so that others know that it's being implemented.

**Pull request merged**
