### PR TITLE
Update repo to reflect focus on C++

### LINKED ISSUE #344: Command make all does not work
[README.md](https://github.com/ProAlgos/ProAlgos-Cpp/blob/42060df5388e99bd8ab3dfaaa4afef67358fe288/C%2B%2B/README.md) in the `C++` directory gives the following directions for building: 

> To compile the source files, run **`make all`**.

However, when I download a fresh copy of the repo and run the command, I see the following:

```
alex ProAlgos-Cpp-master $ cd C++
alex C++ $ make all
make: *** No rule to make target `all'.  Stop.
```

Running `make` and `make default` both appear to have the desired effect. So, I think we should either update the `Makefile` or update `README.md` so that the directions are accurate.

Tagging @faheel since he originally set up CMake on the project.

### LINKED ISSUE #346: Update repo to reflect focus on C++
### Backstory
When @faheel originally started this project, it was imagined that algorithms and data structures would be implemented in multiple languages, with a separate directory for each language. Since then we've changed gears. Now this repo is specifically focused on C++. If and when other languages are added, they'll be added as new repos under the ProAlgos organization.

### Issue
There are many parts of this repo which reflect the fact that it was once designed to house multiple languages. There were general and language-specific documentation files, the code lived in a folder named C++, and so on.

### Proposal
In the interest of reflecting the fact that this repo is solely focused on C++, I've made a variety of changes in #347. Here they are, in summary:

- Consolidate README and contributing documentation (except algorithm-specific READMEs) into the `.github` directory
- Update language to reflect focus of the repo
- Rename `C++` directory to ~`code`~ `cpp`

I believe all of these changes will result in a cleaner repo that is easier for newcomers to access and learn about. I also think that it represents a clearer template on which we can build repos for other languages.

### PR DESCRIPTION
**Pull request by alxmjo**
In short, this PR consolidates our READMEs and contributing documentation and makes several updates to language and folder structure. Please see further commentary in #346. I've elected to keep these as discrete commits (for now) to make it easier to see the specific changes proposed in the PR.

These are significant changes, so I will leave this open for two weeks for reviews, comments, and suggestions.

Closes #346 
Closes #344

### CODE REVIEW

**Comment by alxmjo** [comment]
I can't add you as reviewers, but I'd also be curious to hear input from folks who have contributed recently: @bendanon, @a-moreira, @sylvaus, @rtbowtie.

**Comment by a-moreira** [comment]
I think these are good ideas, mainly the updates in the Contributing and Coding guidelines files. One thing I'd like to see is an explicit link from the main Readme file to the Readme file inside directory where all the algorithms and data structures are listed, so that people arriving at the repo could easily check the code we already have. Another thing is that I don't really see the need to rename the repository from "C++" to "code", actually I think it's less elegant. I'd change it to "cpp" instead of "C++" though, because that's what I usually see in C++ projects (and because it's much easier than typing the plus sign).

**Comment by alxmjo** [comment]
Thanks for the feedback, @a-moreira. When you write... 

> One thing I'd like to see is an explicit link from the main Readme file to the Readme file inside directory where all the algorithms and data structures are listed, so that people arriving at the repo could easily check the code we already have. 

Do you mean (for example) linking from `/README.md` to `/C++/include/algorithm/backtracking/README.md`? If, on the other hand, you mean linking to the README which listed the contents of the repo, please note that I've combined *that* README with the `README.md` at the root of the repo.

> Another thing is that I don't really see the need to rename the repository from "C++" to "code", actually I think it's less elegant. I'd change it to "cpp" instead of "C++" though, because that's what I usually see in C++ projects (and because it's much easier than typing the plus sign).

Good idea. I like `cpp`, too. Thank you.

**Comment by a-moreira** [comment]
@alxmjo Oh, my bad! I didn't notice the change, that's exactly what I meant! :-) combining both README files is a much better idea, actually. Really nice!

**Comment by sylvaus** [comment]
Nice updates.
Would it help and fit the project to add a link to the [C++ core guidelines](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines) in the C++ Coding Guidelines

**Comment by alxmjo** [comment]
Thanks for your feedback, @sylvaus. 

> Would it help and fit the project to add a link to the [C++ core guidelines](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines) in the C++ Coding Guidelines

We have that link at the very top of `CODING_GUIDELINES.md`. 🙂

**Comment by faheel** [comment]
The changes look good @alxmjo! I'll take a closer look at the contents of the Markdown files tomorrow to make sure all sections are up-to-date and all links are valid.

As for now, I'm not sure if it is better to move all top-level documentation files, such as `README.md`, `CODING_GUIDELINES.md` etc. to the `.github` directory because these are applicable everywhere and not just on GitHub (which is what the `.github` directory is for, I believe). I suggest we move the files as follows:

* root directory
  Keep only those files that are conventionally found here, such as `README.md` and `LICENSE.md`.

* `.github`
  Keep those files here that are only applicable on GitHub, such as `PULL_REQUEST_TEMPLATE.md` and `stale.yml`.

* `docs`
  Keep all other top-level documentation and guidelines here, such as `CODING_GUIDELINES.md`, `CONTRIBUTING.md` and `CODE_OF_CONDUCT.md`.

[According to GitHub's docs](https://help.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file#about-default-community-health-files), GitHub will identify the community help files (such as `CONTRIBUTING.md`, `CODE_OF_CONDUCT.md` and `PULL_REQUEST_TEMPLATE.md`) in any of the three directories above, so we can freely decide where we want to place them.

**Comment by alxmjo** [comment]
Thanks for the feedback, @faheel. I've integrated your suggestions. I think everything is accurate and up-to-date, too, but would welcome your offer to double-check.

**Comment by alxmjo** [comment]
Looks I think we've all had an opportunity to look at this and make suggestions, so I'm going to merge this in tomorrow morning (unless something else comes up in the interim).

**Pull request merged**
