### PR TITLE
Polynomial multiplication using linked list added

### PR DESCRIPTION
**Pull request by hkhojasteh**
Based on #177 issue and #178 pull request, I implemented 'Polynomial multiplication using linked list' again (follow all [coding guidelines](https://github.com/faheel/Algos/blob/master/C%2B%2B/CODING_GUIDELINES.md)) in [`reorganise`](https://github.com/faheel/Algos/tree/reorganise). @faheel Be mindful, please.

- [x] Read the [contribution guidelines][contrib-guidelines]
- [ ] Added [unit tests][unit-tests] (or unit tests have already been added)
- [x] Updated the [Contents][contents]

[contrib-guidelines]: https://github.com/faheel/Algos/blob/master/CONTRIBUTING.md
[unit-tests]: https://github.com/faheel/Algos/blob/master/C%2B%2B/UNIT_TESTS.md
[contents]: https://github.com/faheel/Algos/tree/master/C%2B%2B#contents

### CODE REVIEW

**Comment by alxmjo** [comment]
@hkhojasteh Thanks for your submission, Hadi. There are several failing checks. Are you planning on addressing them?

**Comment by hkhojasteh** [comment]
@alxmjo Sure, I was waiting for your review. I will correct this soon.

**Comment by hkhojasteh** [comment]
@alxmjo The codes are almost correct and it takes a long time for this request. Is there any solution to merge this?

**Comment by alxmjo** [comment]
@hkhojasteh Definitely. Just make sure the code meets current standards, namely that source code goes in 
`include` and tests go in `test`. We can do a thorough review once those changes are committed and the Travis tests pass.

**Pull request closed without merging**
