### PR TITLE
Add queue

### LINKED ISSUE #363: Implement Queue Data Structure
Just wanted to add the implementation of a queue.

### PR DESCRIPTION
**Pull request by hafraz07**
Implemented all member functions of a queue(push, pop, length, isEmpty) and added unit tests.

- [ X] Read the [contribution guidelines][contrib-guidelines]
- [X ] Added [unit tests][unit-tests] (or unit tests have already been added)
- [x] Updated the [Contents][contents]

Closes #363 

[contrib-guidelines]: https://github.com/ProAlgos/ProAlgos-Cpp/blob/master/.github/CONTRIBUTING.md
[unit-tests]: https://github.com/ProAlgos/ProAlgos-Cpp/blob/master/.github/CONTRIBUTING.md#adding-unit-tests
[contents]: https://github.com/ProAlgos/ProAlgos-Cpp/blob/master/.github/README.md#contents

### CODE REVIEW

**Comment by alxmjo** [comment]
Thanks for your contribution, @hafraz07. Looks like the build is failing. Please fix that and then I'll move forward with the review.

**Comment by hafraz07** [comment]
Fixed it @alxmjo :)

**Comment by alxmjo** [comment]
Great! I'll have a look shortly.

**Comment by alxmjo** [comment]
And please update the [Contents](https://github.com/ProAlgos/ProAlgos-Cpp/blob/master/README.md#contents).

**Comment by alxmjo** [comment]
Thanks for contributing! 🙂

**Pull request merged**
